export default {
    API: {
        WEATHER_REQUEST: "API/WEATHER_REQUEST",
        WEATHER_SUCCESS: "API/WEATHER_SUCCESS",
        FORECAST_REQUEST: "API/FORECAST_REQUEST",
        FORECAST_SUCCESS: "API/FORECAST_SUCCESS"
    }
};
